name: Build and deploy JAR app to Azure Web App - javawebapponepiece

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: artifact

      - name: List files (debug)
        run: ls -R artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E1943927DFEB42BAACF3931BBC13A225 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3557E315BCD84DEDBD9ADB44F0FEE243 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AADB496B7B0A4361A96277EFE70CC2D9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: javawebapponepiece
          slot-name: Production
          package: artifact/*.jar
